# Assignment 3

T1.1. Write a function to compute 5/0 and use try/except to catch the exceptions

In [37]:
a=5
b=0
try:
  print(a/b)
except Exception:
  print("Hello, you can't divide a number by a zero")

Hello, you can't divide a number by a zero


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].


In [4]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","cricket"]

# Use list comprehension instead of looping over each of the predicates
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
 print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


T2.1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [18]:
x = np.array([100,215,375,487,567])
N = 3
np.vander(x, N)

array([[ 10000,    100,      1],
       [ 46225,    215,      1],
       [140625,    375,      1],
       [237169,    487,      1],
       [321489,    567,      1]])

In [14]:
x = np.array([10,205,375,485,567])
N = 4
np.column_stack([x**(N-1-i) for i in range(N)])

array([[     1000,       100,        10,         1],
       [  8615125,     42025,       205,         1],
       [ 52734375,    140625,       375,         1],
       [114084125,    235225,       485,         1],
       [182284263,    321489,       567,         1]], dtype=int32)

In [30]:
x = np.array([10,8,7,6,5])
N =5
np.vander(x, N)

array([[10000,  1000,   100,    10,     1],
       [ 4096,   512,    64,     8,     1],
       [ 2401,   343,    49,     7,     1],
       [ 1296,   216,    36,     6,     1],
       [  625,   125,    25,     5,     1]])